### PR TITLE
Update env var names

### PR DESCRIPTION
**Pull request by sei-byoung**

### CODE REVIEW

**Comment by sei-ebram** [comment]
@sei-byoung did you talk about this with the team?  Personally I think I'd prefer it just be IDENTITY_ instead of including SEI_, but then again you are correct that this is specific to our CMU/SEI Identity provider.  I feel torn, but because of the latter, I'm approving :)

**Review by sei-ebram — APPROVED** [review]

**Comment by sei-ebram** [comment]
We need to keep track of all the instances where this is being used so that we don't miss updating the env vars in those locations

**Comment by sei-byoung** [comment]
> 
> 
> @sei-byoung did you talk about this with the team? Personally I think I'd prefer it just be IDENTITY_ instead of including SEI_, but then again you are correct that this is specific to our CMU/SEI Identity provider. I feel torn, but because of the latter, I'm approving :)

I'm basing the names off of this Jira ticket: https://issues.sei.cmu.edu/jira/browse/CRU-1135
I would be OK with including or not including the SEI prefix. It's up to you guys.

**Comment by sei-ebram** [comment]
> > @sei-byoung did you talk about this with the team? Personally I think I'd prefer it just be IDENTITY_ instead of including SEI_, but then again you are correct that this is specific to our CMU/SEI Identity provider. I feel torn, but because of the latter, I'm approving :)
> 
> I'm basing the names off of this Jira ticket: https://issues.sei.cmu.edu/jira/browse/CRU-1135
> I would be OK with including or not including the SEI prefix. It's up to you guys.

That works for me, just felt like it was worth a discussion, thanks for the info :)

**Review by sei-tspencer — APPROVED** [review]

**Comment by sei-aschlackman** [comment]
> > > @sei-byoung did you talk about this with the team? Personally I think I'd prefer it just be IDENTITY_ instead of including SEI_, but then again you are correct that this is specific to our CMU/SEI Identity provider. I feel torn, but because of the latter, I'm approving :)
> > 
> > 
> > I'm basing the names off of this Jira ticket: https://issues.sei.cmu.edu/jira/browse/CRU-1135
> > I would be OK with including or not including the SEI prefix. It's up to you guys.
> 
> That works for me, just felt like it was worth a discussion, thanks for the info :)

if you have a better name, i'm all ears, but at least it's not ambiguous this way.

**Review by sei-aschlackman — APPROVED** [review]

**Review by sei-noconnor — APPROVED** [review]

**Pull request merged**
